### ISSUE TITLE
Questions about RocksDB Space Amplification Factor

### ISSUE THREAD

**Issue by rlagnlrns** [addb-swstarlab/K2vTune#15]
Hello,

I recently studied RockDB and often use the command "compact" in my experiments. I have a hard time understanding how does it related with Space Amplification Factor(SAF). 

Thanks.

**Comment by JIEUN-12** [comment]
Does the "compact" mean an operation of db_bench options, [here](https://github.com/EighteenZi/rocksdb_wiki/blob/master/Benchmarking-tools.md)?
According to the document, it means compaction the entire DB.

To be specific, when I add the "compact" option to the "benchmarks" options, the levels of RocksDB were compacted to the lowest level(if # of level is 3, the data will be saved on L3).

Unfortunately, I can't really explain the relation between SAF and the "compact" option. I guess that the sizes of those each levels would be highly related to the "compact" option.

I recommend checking out [the official website](https://github.com/EighteenZi/rocksdb_wiki/tree/master) to answer any remained questions you may have.

**Comment by huijunjin** [comment]
Thank you, it helped a lot.
